// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMFHvejtnodwkzoYOCoKV54uQdFkZl1fc',
    appId: '1:387318523179:web:d773d9ddca696556e0d16e',
    messagingSenderId: '387318523179',
    projectId: 'kopa-358fe',
    authDomain: 'kopa-358fe.firebaseapp.com',
    storageBucket: 'kopa-358fe.firebasestorage.app',
    measurementId: 'G-PYG7F5KDS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdMoySXYKCqBhZsqqnP-4YpxUPoijmVYU',
    appId: '1:387318523179:android:d5ef70ca25f6ed43e0d16e',
    messagingSenderId: '387318523179',
    projectId: 'kopa-358fe',
    storageBucket: 'kopa-358fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEGNYTgNI41c6yClVnfa30ZVRy01_eujE',
    appId: '1:387318523179:ios:616c2b9d1b91c7bae0d16e',
    messagingSenderId: '387318523179',
    projectId: 'kopa-358fe',
    storageBucket: 'kopa-358fe.firebasestorage.app',
    iosBundleId: 'kopa.app',
  );
}
